# This is a basic workflow to help you get started with Actions

name: auto_generate_header

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      module:
        description: 'module name'
        required: true
        default: ''
      version:
        description: 'version'
        required: true
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Install Cocoapods
        run: sudo gem install cocoapods

      - name: pod
        run:  |
          pod repo add-cdn trunk https://cdn.cocoapods.org/
          pod repo
          pod setup

      # Runs a single command using the runners shell
      - name: auto 
        run: |
          python main.py ${{ github.event.inputs.module }} ${{ github.event.inputs.version }}

      - name: doxygen
        uses: mattnotmitt/doxygen-action@v1.2.3
        with: 
            working-directory: ./submodule
            doxyfile-path: ./Doxyfile
      # Runs a set of commands using the runners shell
      - name: commit
        run: |
          git config --global user.name ll
          git config --global user.email 123@qq.com
          git add .
          git commit -m "自动生成文档" 
          git push
